packet/bgp: use strconv.ParseUint instead of strconv.Atoi()
Atoi() returns a signed int. On a 32-bit platform, this is not big
enough to fit an unsigned 32-bit int. Replace all occurrences of
Atoi() to ParseUint() with the appropriate size as a parameter.

This fix this failure:

```
--- FAIL: Test_ParseEthernetSegmentIdentifier (0.00s)
        Error Trace:    bgp_test.go:1181
        Error:          Expected nil, but got: &errors.errorString{s:"invalid esi values for type ESI_AS: [2864434397 287454020]"}

        Error Trace:    bgp_test.go:1182
        Error:          Not equal: bgp.EthernetSegmentIdentifier{Type:0x5, Value:[]uint8{0xaa, 0xbb, 0xcc, 0xdd, 0x11, 0x22, 0x33, 0x44, 0x0}} (expected)
                                != bgp.EthernetSegmentIdentifier{Type:0x5, Value:[]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}} (actual)

                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,2 +1,2 @@
                        -(bgp.EthernetSegmentIdentifier) ESI_AS | as 2864434397, local discriminator 287454020
                        +(bgp.EthernetSegmentIdentifier) ESI_AS | as 0, local discriminator 0

FAIL
FAIL    github.com/osrg/gobgp/packet/bgp        0.003s
```