test: Pin requests==2.25.1 to maintain compatibility with docker-py
Versions of requests >= 2.26.0 introduce changes that break
functionality in docker-py:

docker.errors.DockerException: Error while fetching server API
version: Not supported URL scheme http+docker

Signed-off-by: FUJITA Tomonori <fujita.tomonori@gmail.com>